### ISSUE TITLE
AiderDrop command ?

### ISSUE THREAD

**Issue by williamgoulois** [aweis89/aider.nvim#5]
Could you consider adding drop current buffer ?
Or maybe we can use `AiderSend /drop` and passing the current file path ?

**Comment by williamgoulois** [comment]
I managed to do it like this 

```lua
      {
        "<leader>ad",
        function()
          local current_file = vim.fn.expand('%:p')
          vim.cmd('AiderSend /drop ' .. current_file)
        end,
        desc = "Drop current file from aider",
        mode = "n",
      },
```

**Comment by aweis89** [comment]
I've been thinking about adding some additional features around dropping files. What I'd really like to do is have a telescope file picker that shows all current files loaded in aider with keymap to drop selected files.

Maybe I'll add an example to the readme of using `AiderSend` to drop files, though I think that particular mapping is a little too specific to have in the plugin itself.
